
# Expected inputs:
# raw_images = [...]
# deskewed_images = [...]

rows = len(deskewed_images)
plt.figure(figsize=(12, rows * 5))

for img_idx, (raw_original, raw_img) in enumerate(zip(raw_images, deskewed_images)):
    # -*- coding: utf-8 -*-
    """Untitled1.ipynb

    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/15IbCWeHNzCIIcyRaT8bOL1sLkQ6kLPju
    """

    # =====================================================================
    # 1. PREPROCESSING (Clean Edge & Shape Discovery)
    # =====================================================================

    black_canvas = np.zeros_like(raw_img)
    canny = cv.Canny(raw_img, 100, 200)
    # Run a small closing operation to fuse any tiny gaps in the lines
    # 1. Standard Preprocessing
    gray  = cv.cvtColor(raw_img, cv.COLOR_BGR2GRAY)
    blur  = cv.GaussianBlur(gray, (5, 5), 0)

    # Standard adaptive threshold (catches black outlines on white background)
    # REPLACE with this — blockSize scales with image width automatically
    block = int(raw_img.shape[1] * 0.02)          # 2% of image width
    block = block if block % 2 == 1 else block + 1 # must be odd number
    block = max(block, 11)                          # never go below 11

    thresh_light = cv.adaptiveThreshold(
        blur, 255, cv.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv.THRESH_BINARY_INV, block, 3
    )

    # ── NEW: also catch dark-filled shapes like the black torso circle ───
    # Otsu finds the best global threshold automatically
    _, thresh_dark = cv.threshold(blur, 0, 255, cv.THRESH_BINARY_INV + cv.THRESH_OTSU)

    # Merge both masks — now both light-outline and dark-filled shapes detected
    thresh = cv.bitwise_or(thresh_light, thresh_dark)

    kernel       = cv.getStructuringElement(cv.MORPH_RECT, (3, 3))
    thresh_healed = cv.morphologyEx(thresh, cv.MORPH_CLOSE, kernel)

    # 3. Find Contours using the healed image
    contours, hierarchy = cv.findContours(
        thresh_healed, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE
    )



    # =====================================================================
    # 2. FILTERING TEXT & DETECTING UNIQUE TARGET SHAPES
    # =====================================================================

    # ── Image scale factor — all thresholds derive from this ────────────
    # Everything is relative to image area so any resolution works
    IMG_AREA      = raw_img.shape[0] * raw_img.shape[1]
    IMG_DIAG      = (raw_img.shape[0]**2 + raw_img.shape[1]**2) ** 0.5

    # Scale-relative thresholds (tune the multipliers, not the raw numbers)
    MIN_AREA      = IMG_AREA * 0.002
    PERIM_LARGE   = IMG_DIAG * 0.5
    SPIKE_MAX_LEN = IMG_DIAG * 0.1
    TOLERANCE_PX  = int(IMG_DIAG * 0.02)

    unique_contours = []
    seen_boxes = []
    detected_objects = []
    for cnt in contours:
        area = cv.contourArea(cnt)
        perimeter = cv.arcLength(cnt, True)
        # 1. Skip tiny noise and small artifacts
        if area < MIN_AREA:
            continue

        compactness = (perimeter ** 2) / area if area > 0 else 9999
        if compactness > 500 and area < IMG_AREA * 0.05:      # tune up if real shapes get filtered, down if noise stays
            continue

        x, y, w, h = cv.boundingRect(cnt)

        # Calculate aspect ratio
        aspect_ratio = float(w) / h if h > 0 else 0

        # FIX CONTOUR #2: Instantly drop thin line fragments
        if aspect_ratio < 0.15 or aspect_ratio > 6.0:
            continue

        # Calculate solidity
        hull = cv.convexHull(cnt)
        hull_area = cv.contourArea(hull)
        solidity = float(area) / hull_area if hull_area > 0 else 0

        # Skip low solidity text layout lines
        if solidity < 0.40:
            continue

        # 2. Deduplicate close edge tracks
        is_duplicate = False
        for sx, sy, sw, sh in seen_boxes:
            if (abs(x - sx) < TOLERANCE_PX and
                abs(y - sy) < TOLERANCE_PX and
                abs(w - sw) < TOLERANCE_PX and
                abs(h - sh) < TOLERANCE_PX):
                is_duplicate = True
                break

        if not is_duplicate:
            seen_boxes.append((x, y, w, h))

            # 1. Math Check: Is this a round circle or a polygon shape?
            ellipse = cv.fitEllipse(cnt) if len(cnt) >= 5 else None
            is_circle = False

            if ellipse:
                (_, _), (ew, eh), _ = ellipse
                circle_ratio = float(ew) / eh if eh > 0 else 0

                rect = cv.minAreaRect(cnt)
                rect_area = rect[1][0] * rect[1][1]
                rect_extent = float(area) / rect_area if rect_area > 0 else 0

                test_epsilon = 0.01 * cv.arcLength(cnt, True)
                test_approx = cv.approxPolyDP(cnt, test_epsilon, True)
                num_vertices = len(test_approx)

                if (0.65 < circle_ratio < 1.50 and
                    0.72 <= rect_extent <= 0.82 and
                    num_vertices > 8 and
                    solidity > 0.95):
                    is_circle = True
            else:
                test_epsilon = 0.01 * cv.arcLength(cnt, True)
                test_approx  = cv.approxPolyDP(cnt, test_epsilon, True)
                num_vertices = len(test_approx)

            # ── Classify shape type ──────────────────────────────────
            if is_circle:
                (_, _), (ew, eh), _ = ellipse
                cr = float(ew) / eh if eh > 0 else 0
                shape_type = "circle" if 0.90 < cr < 1.10 else "ellipse"


            # ── Build clean contour ──────────────────────────────────
            contour_to_add = None

            if is_circle:
                smooth = cv.ellipse2Poly(
                    (int(ellipse[0][0]), int(ellipse[0][1])),
                    (int(ew / 2), int(eh / 2)),
                    int(ellipse[2]),
                    0, 360, 4
                )
                contour_to_add = smooth.reshape(-1, 1, 2)

            else:
                perimeter = cv.arcLength(cnt, True)

                if perimeter > PERIM_LARGE:
                    isolated_canvas = np.zeros_like(thresh_healed)
                    cv.drawContours(isolated_canvas, [cnt], -1, 255, -1)

                    k_size = np.clip(
                        int(perimeter * 0.003) + (1 if int(perimeter * 0.003) % 2 == 0 else 0),
                        3, 15
                    )
                    kernel_e = cv.getStructuringElement(cv.MORPH_ELLIPSE, (k_size, k_size))
                    cleaned_canvas = cv.morphologyEx(isolated_canvas, cv.MORPH_OPEN,  kernel_e)
                    cleaned_canvas = cv.morphologyEx(cleaned_canvas,  cv.MORPH_CLOSE, kernel_e)

                    smoothed_contours, _ = cv.findContours(
                        cleaned_canvas, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE
                    )

                    if smoothed_contours:
                        main_smoothed_cnt = max(smoothed_contours, key=cv.contourArea)
                        current_area = cv.contourArea(cnt)
                        largest_area = max([cv.contourArea(c) for c in unique_contours]) if unique_contours else 0

                        if current_area >= largest_area:
                            epsilon = 0.005 * cv.arcLength(main_smoothed_cnt, True)
                            approx  = cv.approxPolyDP(main_smoothed_cnt, epsilon, True)

                            # --- NEW: Get bounding dimensions to protect shoulders ---
                            x_box, y_box, w_box, h_box = cv.boundingRect(main_smoothed_cnt)

                            idx = 0
                            while idx < len(approx) and len(approx) > 4:
                                p_curr = approx[idx][0]
                                p_prev = approx[idx - 1][0]
                                p_next = approx[(idx + 1) % len(approx)][0]

                                len_prev = np.linalg.norm(p_curr - p_prev)
                                len_next = np.linalg.norm(p_curr - p_next)

                                if len_prev < SPIKE_MAX_LEN and len_next < SPIKE_MAX_LEN:
                                    v1 = p_prev - p_curr
                                    v2 = p_next - p_curr
                                    cos_angle = np.dot(v1, v2) / (
                                        np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-6
                                    )
                                    angle = np.degrees(np.arccos(np.clip(cos_angle, -1.0, 1.0)))

                                    # ---------------------------------------------------------
                                    # SHOULDER PROTECTION GUARDRAIL
                                    # Identify if the vertex is in the upper shoulder zones:
                                    # Top ~35% of the target height, and outer 30% of left/right width.
                                    # ---------------------------------------------------------
                                    is_in_shoulder_zone = (
                                        (p_curr[1] < y_box + h_box * 0.35) and
                                        ((p_curr[0] < x_box + w_box * 0.30) or (p_curr[0] > x_box + w_box * 0.70))
                                    )

                                    # Only delete the spike if it's NOT a protected shoulder corner
                                    if angle < 115 and not is_in_shoulder_zone:
                                        approx = np.delete(approx, idx, axis=0)
                                        continue
                                idx += 1
                            contour_to_add = approx

                        else:
                            # Inner ring — keep it, apply convex hull to clean it
                            hull = cv.convexHull(main_smoothed_cnt)
                            epsilon = 0.01 * cv.arcLength(hull, True)
                            contour_to_add = cv.approxPolyDP(hull, epsilon, True)

                else:
                    clean_hull = cv.convexHull(cnt)
                    epsilon    = 0.006 * cv.arcLength(clean_hull, True)
                    contour_to_add = cv.approxPolyDP(clean_hull, epsilon, True)

            # ── Single append point — lists always stay in sync ──────
            # ── Single append point — classify AFTER all cleaning ────
            if contour_to_add is not None:

                # Count vertices on the FINAL cleaned contour, not the raw one
                # This gives accurate vertex count after bullet hole fixing
                if is_circle:
                    (_, _), (ew, eh), _ = ellipse
                    cr = float(ew) / eh if eh > 0 else 0
                    shape_type = "circle" if 0.90 < cr < 1.10 else "ellipse"
                else:
                    # Re-approximate the final contour at a clean epsilon
                    final_epsilon  = 0.02 * cv.arcLength(contour_to_add, True)
                    final_approx   = cv.approxPolyDP(contour_to_add, final_epsilon, True)
                    final_vertices = len(final_approx)

                    if final_vertices == 3:
                        shape_type = "triangle"
                    elif final_vertices == 4:
                        shape_type = "square" if 0.90 < aspect_ratio < 1.10 else "rectangle"
                    elif final_vertices <= 8:
                        shape_type = f"polygon ({final_vertices} pts)"
                    else:
                        shape_type = "polygon"

                unique_contours.append(contour_to_add)
                detected_objects.append({
                    "type":  shape_type,
                    "index": len(unique_contours) - 1,
                    "area":  cv.contourArea(contour_to_add)
                })


    # =====================================================================
    # POST-LOOP NOISE REMOVAL
    # Remove shapes that are too small relative to the largest detected shape
    # This kills corner smudges/shadows that passed all per-contour filters
    # =====================================================================
    if unique_contours:
        largest_area = max(obj["area"] for obj in detected_objects)

        # Keep only shapes that are at least 2% of the largest shape's area
        # Tune DOWN to 0.01 if small real shapes get removed
        # Tune UP to 0.05 if noise still slips through
        MIN_RELATIVE_AREA = largest_area * 0.02

        filtered_pairs = [
            (cnt, obj)
            for cnt, obj in zip(unique_contours, detected_objects)
            if obj["area"] >= MIN_RELATIVE_AREA
        ]

        if filtered_pairs:
            unique_contours, detected_objects = map(list, zip(*filtered_pairs))
        else:
            unique_contours, detected_objects = [], []

    # =====================================================================
    # 3. DYNAMIC PLOTTING GRID (View All Discovered Shapes Separately)
    # =====================================================================
    num_contours = len(unique_contours)

    num_contours = len(unique_contours)

    if num_contours == 0:
        print("No target shapes found to plot!")
    else:
        cols = min(4, num_contours)
        rows = math.ceil(num_contours / cols)
        plt.figure(figsize=(cols * 4, rows * 4))

        for i, cnt in enumerate(unique_contours):
            single_canvas = np.zeros_like(black_canvas, dtype=np.uint8)
            cv.drawContours(single_canvas, [cnt], -1, (0, 0, 255), 3)

            x, y, w, h = cv.boundingRect(cnt)
            area = cv.contourArea(cnt)

            # Look up shape type — fall back gracefully if lists mismatch
            shape_type = detected_objects[i]["type"] if i < len(detected_objects) else "unknown"

            plt.subplot(rows, cols, i + 1)
            plt.imshow(cv.cvtColor(single_canvas, cv.COLOR_BGR2RGB))
            plt.title(
                f"#{i+1} — {shape_type}\nArea: {int(area)}  |  {w}×{h}",
                fontsize=10
            )
            plt.axis('off')

        plt.tight_layout()
        plt.show()

    print(f"Number of clean target shapes detected: {num_contours}"
    overlay = raw_img.copy()
    cv.drawContours(overlay, unique_contours, -1, (0,0,255), 3)

    plt.subplot(rows,2,2*img_idx+1)
    plt.imshow(cv.cvtColor(raw_original, cv.COLOR_BGR2RGB))
    plt.title(f"Raw Image #{img_idx+1}")
    plt.axis("off")

    plt.subplot(rows,2,2*img_idx+2)
    plt.imshow(cv.cvtColor(overlay, cv.COLOR_BGR2RGB))
    plt.title(f"{len(unique_contours)} Shapes Detected")
    plt.axis("off")

    print(f"Image {img_idx+1}: {len(unique_contours)} clean target shapes detected")

plt.tight_layout()
plt.show()
