# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zNk1uPe0Pmy6QGbvviN-QhvHFz6VbMv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv
import math
from matplotlib.colors import Colormap
raw_img= cv.imread("/content/WhatsApp Image 2026-06-25 at 3.52.30 AM (2).jpeg")
image_paths = [
    "/content/IDPA-Green__94733gg.png",
    "/content/Screenshot 2026-06-22.png",
    "/content/up green hole.jpeg",
    "/content/side greeen hole.jpeg",
    "/content/side black hole.jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.32 AM (4).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.32 AM.jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.33 AM (1).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.33 AM (2).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.33 AM (3).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.33 AM.jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.34 AM (1).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.34 AM (3).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.35 AM (1).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.35 AM (2).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.35 AM.jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.37 AM (1).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.37 AM (2).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.38 AM.jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.29 AM.jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.30 AM (1).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.30 AM (2).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.30 AM (3).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.30 AM.jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.31 AM (1).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.31 AM (2).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.31 AM.jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.32 AM (1).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.32 AM (2).jpeg",
    "/content/WhatsApp Image 2026-06-25 at 3.52.32 AM (3).jpeg",
]

# =====================================================================
# HELPER — full shape detection pipeline, wrapped as a reusable function
# (ported as-is from your main detection loop, just parameterized on `img`)
# =====================================================================
def detect_target_shapes(img):
    """
    Runs the full contour detection & shape classification pipeline on a
    single image. Returns (unique_contours, detected_objects).
    """
    gray  = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    blur  = cv.GaussianBlur(gray, (5, 5), 0)

    block = int(img.shape[1] * 0.02)
    block = block if block % 2 == 1 else block + 1
    block = max(block, 11)

    thresh_light = cv.adaptiveThreshold(
        blur, 255, cv.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv.THRESH_BINARY_INV, block, 3
    )

    _, thresh_dark = cv.threshold(blur, 0, 255, cv.THRESH_BINARY_INV + cv.THRESH_OTSU)
    thresh = cv.bitwise_or(thresh_light, thresh_dark)

    kernel        = cv.getStructuringElement(cv.MORPH_RECT, (3, 3))
    thresh_healed = cv.morphologyEx(thresh, cv.MORPH_CLOSE, kernel)

    contours, hierarchy = cv.findContours(
        thresh_healed, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE
    )

    IMG_AREA      = img.shape[0] * img.shape[1]
    IMG_DIAG      = (img.shape[0]**2 + img.shape[1]**2) ** 0.5

    MIN_AREA      = IMG_AREA * 0.002
    PERIM_LARGE   = IMG_DIAG * 0.5
    SPIKE_MAX_LEN = IMG_DIAG * 0.1
    TOLERANCE_PX  = int(IMG_DIAG * 0.02)

    unique_contours   = []
    seen_boxes        = []
    detected_objects  = []

    for cnt in contours:
        area = cv.contourArea(cnt)
        perimeter = cv.arcLength(cnt, True)
        if area < MIN_AREA:
            continue

        compactness = (perimeter ** 2) / area if area > 0 else 9999
        if compactness > 500 and area < IMG_AREA * 0.05:
            continue

        x, y, w, h = cv.boundingRect(cnt)
        aspect_ratio = float(w) / h if h > 0 else 0
        if aspect_ratio < 0.15 or aspect_ratio > 6.0:
            continue

        hull = cv.convexHull(cnt)
        hull_area = cv.contourArea(hull)
        solidity = float(area) / hull_area if hull_area > 0 else 0
        if solidity < 0.40:
            continue

        is_duplicate = False
        for sx, sy, sw, sh in seen_boxes:
            if (abs(x - sx) < TOLERANCE_PX and
                abs(y - sy) < TOLERANCE_PX and
                abs(w - sw) < TOLERANCE_PX and
                abs(h - sh) < TOLERANCE_PX):
                is_duplicate = True
                break

        if not is_duplicate:
            seen_boxes.append((x, y, w, h))

            ellipse = cv.fitEllipse(cnt) if len(cnt) >= 5 else None
            is_circle = False

            if ellipse:
                (_, _), (ew, eh), _ = ellipse
                circle_ratio = float(ew) / eh if eh > 0 else 0

                rect = cv.minAreaRect(cnt)
                rect_area = rect[1][0] * rect[1][1]
                rect_extent = float(area) / rect_area if rect_area > 0 else 0

                test_epsilon = 0.01 * cv.arcLength(cnt, True)
                test_approx = cv.approxPolyDP(cnt, test_epsilon, True)
                num_vertices = len(test_approx)

                if (0.65 < circle_ratio < 1.50 and
                    0.72 <= rect_extent <= 0.82 and
                    num_vertices > 8 and
                    solidity > 0.95):
                    is_circle = True
            else:
                test_epsilon = 0.01 * cv.arcLength(cnt, True)
                test_approx  = cv.approxPolyDP(cnt, test_epsilon, True)
                num_vertices = len(test_approx)

            if is_circle:
                (_, _), (ew, eh), _ = ellipse
                cr = float(ew) / eh if eh > 0 else 0
                shape_type = "circle" if 0.90 < cr < 1.10 else "ellipse"

            contour_to_add = None

            if is_circle:
                smooth = cv.ellipse2Poly(
                    (int(ellipse[0][0]), int(ellipse[0][1])),
                    (int(ew / 2), int(eh / 2)),
                    int(ellipse[2]),
                    0, 360, 4
                )
                contour_to_add = smooth.reshape(-1, 1, 2)

            else:
                perimeter = cv.arcLength(cnt, True)

                if perimeter > PERIM_LARGE:
                    isolated_canvas = np.zeros_like(thresh_healed)
                    cv.drawContours(isolated_canvas, [cnt], -1, 255, -1)

                    k_size = np.clip(
                        int(perimeter * 0.003) + (1 if int(perimeter * 0.003) % 2 == 0 else 0),
                        3, 15
                    )
                    kernel_e = cv.getStructuringElement(cv.MORPH_ELLIPSE, (k_size, k_size))
                    cleaned_canvas = cv.morphologyEx(isolated_canvas, cv.MORPH_OPEN,  kernel_e)
                    cleaned_canvas = cv.morphologyEx(cleaned_canvas,  cv.MORPH_CLOSE, kernel_e)

                    smoothed_contours, _ = cv.findContours(
                        cleaned_canvas, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE
                    )

                    if smoothed_contours:
                        main_smoothed_cnt = max(smoothed_contours, key=cv.contourArea)
                        current_area = cv.contourArea(cnt)
                        largest_area = max([cv.contourArea(c) for c in unique_contours]) if unique_contours else 0

                        if current_area >= largest_area:
                            epsilon = 0.005 * cv.arcLength(main_smoothed_cnt, True)
                            approx  = cv.approxPolyDP(main_smoothed_cnt, epsilon, True)

                            x_box, y_box, w_box, h_box = cv.boundingRect(main_smoothed_cnt)

                            idx = 0
                            while idx < len(approx) and len(approx) > 4:
                                p_curr = approx[idx][0]
                                p_prev = approx[idx - 1][0]
                                p_next = approx[(idx + 1) % len(approx)][0]

                                len_prev = np.linalg.norm(p_curr - p_prev)
                                len_next = np.linalg.norm(p_curr - p_next)

                                if len_prev < SPIKE_MAX_LEN and len_next < SPIKE_MAX_LEN:
                                    v1 = p_prev - p_curr
                                    v2 = p_next - p_curr
                                    cos_angle = np.dot(v1, v2) / (
                                        np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-6
                                    )
                                    angle = np.degrees(np.arccos(np.clip(cos_angle, -1.0, 1.0)))

                                    in_upper_zone = (p_curr[1] < y_box + h_box * 0.40)

                                    in_head_zone = (
                                        (p_curr[1] < y_box + h_box * 0.25) and
                                        (p_curr[0] > x_box + w_box * 0.35) and
                                        (p_curr[0] < x_box + w_box * 0.65)
                                    )

                                    is_shoulder_corner = (
                                        (p_curr[1] < y_box + h_box * 0.40) and
                                        ((p_curr[0] < x_box + w_box * 0.30) or (p_curr[0] > x_box + w_box * 0.70))
                                    )

                                    should_protect = in_upper_zone or in_head_zone or is_shoulder_corner

                                    if angle < 115 and not should_protect:
                                        approx = np.delete(approx, idx, axis=0)
                                        continue
                                idx += 1
                            contour_to_add = approx

                        else:
                            hull = cv.convexHull(main_smoothed_cnt)
                            epsilon = 0.01 * cv.arcLength(hull, True)
                            contour_to_add = cv.approxPolyDP(hull, epsilon, True)

                else:
                    clean_hull = cv.convexHull(cnt)
                    epsilon    = 0.006 * cv.arcLength(clean_hull, True)
                    contour_to_add = cv.approxPolyDP(clean_hull, epsilon, True)

            if contour_to_add is not None:
                if is_circle:
                    (_, _), (ew, eh), _ = ellipse
                    cr = float(ew) / eh if eh > 0 else 0
                    shape_type = "circle" if 0.90 < cr < 1.10 else "ellipse"
                else:
                    final_epsilon  = 0.02 * cv.arcLength(contour_to_add, True)
                    final_approx   = cv.approxPolyDP(contour_to_add, final_epsilon, True)
                    final_vertices = len(final_approx)

                    if final_vertices == 3:
                        shape_type = "triangle"
                    elif final_vertices == 4:
                        shape_type = "square" if 0.90 < aspect_ratio < 1.10 else "rectangle"
                    elif final_vertices <= 8:
                        shape_type = f"polygon ({final_vertices} pts)"
                    else:
                        shape_type = "polygon"

                unique_contours.append(contour_to_add)
                detected_objects.append({
                    "type":  shape_type,
                    "index": len(unique_contours) - 1,
                    "area":  cv.contourArea(contour_to_add)
                })

    # POST-LOOP NOISE REMOVAL
    if unique_contours:
        largest_area = max(obj["area"] for obj in detected_objects)
        MIN_RELATIVE_AREA = largest_area * 0.02

        filtered_pairs = [
            (cnt, obj)
            for cnt, obj in zip(unique_contours, detected_objects)
            if obj["area"] >= MIN_RELATIVE_AREA
        ]

        if filtered_pairs:
            unique_contours, detected_objects = map(list, zip(*filtered_pairs))
        else:
            unique_contours, detected_objects = [], []

    return unique_contours, detected_objects


# =====================================================================
# PERSPECTIVE — your completed octagon-corner-recovery pipeline
# (unchanged from what we just finished)
# =====================================================================
def get_octagon_corners(poly, img_shape, debug=False):
    pts = poly.reshape(-1, 2).astype(np.float64)
    n = len(pts)

    if n != 8:
        raise ValueError(f"Expected exactly 8 vertices for alternating side/cut structure, got {n}")

    edge_lengths = []
    for i in range(8):
        p1, p2 = pts[i], pts[(i + 1) % 8]
        edge_lengths.append(np.linalg.norm(p2 - p1))

    sum_even = sum(edge_lengths[0::2])
    sum_odd  = sum(edge_lengths[1::2])
    side_start = 0 if sum_even > sum_odd else 1
    side_edge_idxs = [(side_start + 2*k) % 8 for k in range(4)]

    if debug:
        print(f"Edge lengths (cyclic): {[round(l,1) for l in edge_lengths]}")
        print(f"side edges at idx {side_edge_idxs}")

    sides = []
    for i in side_edge_idxs:
        p1, p2 = pts[i], pts[(i + 1) % 8]
        mid = (p1 + p2) / 2
        sides.append({"p1": p1, "p2": p2, "mid": mid})

    sides_by_y = sorted(sides, key=lambda s: s["mid"][1])
    top_side    = sides_by_y[0]
    bottom_side = sides_by_y[-1]
    remaining   = sides_by_y[1:-1]

    remaining_by_x = sorted(remaining, key=lambda s: s["mid"][0])
    left_side  = remaining_by_x[0]
    right_side = remaining_by_x[-1]

    classified = {
        "top":    (top_side["p1"], top_side["p2"]),
        "bottom": (bottom_side["p1"], bottom_side["p2"]),
        "left":   (left_side["p1"], left_side["p2"]),
        "right":  (right_side["p1"], right_side["p2"]),
    }

    if debug:
        for name in ["top", "right", "bottom", "left"]:
            print(f"  {name}: mid={classified[name][0].round(1)}->{classified[name][1].round(1)}")

    def line_from_pts(p1, p2):
        x1, y1 = p1; x2, y2 = p2
        a = y2 - y1; b = x1 - x2
        c = -(a*x1 + b*y1)
        return a, b, c

    def intersect(l1, l2):
        a1,b1,c1 = l1; a2,b2,c2 = l2
        det = a1*b2 - a2*b1
        if abs(det) < 1e-9:
            return None
        return np.array([(b1*c2-b2*c1)/det, (a2*c1-a1*c2)/det])

    L_top, L_bottom = line_from_pts(*classified["top"]), line_from_pts(*classified["bottom"])
    L_left, L_right = line_from_pts(*classified["left"]), line_from_pts(*classified["right"])

    TL, TR = intersect(L_top, L_left), intersect(L_top, L_right)
    BR, BL = intersect(L_bottom, L_right), intersect(L_bottom, L_left)

    if any(p is None for p in (TL, TR, BR, BL)):
        raise ValueError("Failed to intersect one or more side pairs (near-parallel lines).")

    if debug:
        print("Corners (TL,TR,BR,BL):", TL, TR, BR, BL)

    return np.array([TL, TR, BR, BL], dtype=np.float32)


def expand_quad_to_fit_contour(quad_corners, target_points, padding_ratio=0.0, max_scale=2.5):
    """
    Same as before, but now caps the scale factor — if the required
    expansion exceeds max_scale, it's almost certainly being driven by
    an outlier point (wall edge, shadow, tape) rather than the real
    torso silhouette, so we clip rather than blow up the canvas.
    """
    quad = np.asarray(quad_corners, dtype=np.float64)
    pts  = np.asarray(target_points, dtype=np.float64).reshape(-1, 2)

    C = quad.mean(axis=0)
    edges = [(quad[0], quad[1]), (quad[1], quad[2]), (quad[2], quad[3]), (quad[3], quad[0])]

    required_k = 1.0
    for p1, p2 in edges:
        d = p2 - p1
        normal = np.array([d[1], -d[0]])
        normal = normal / (np.linalg.norm(normal) + 1e-12)
        if np.dot(normal, C - p1) > 0:
            normal = -normal
        m = -np.dot(normal, C - p1)
        if m < 1e-9:
            continue
        g_pts = (pts - p1) @ normal
        k_needed = 1.0 + g_pts / m
        required_k = max(required_k, np.max(k_needed))

    k_final = required_k * (1.0 + padding_ratio)

    # ── SAFETY CLAMP ──────────────────────────────────────────────
    if k_final > max_scale:
        print(f"  [warn] expansion scale {k_final:.2f} exceeds max_scale={max_scale}, "
              f"clamping (likely outlier point in torso contour)")
        k_final = max_scale
    # ──────────────────────────────────────────────────────────────

    expanded = C + k_final * (quad - C)
    return expanded.astype(np.float32), k_final


def warp_from_corners(raw_img, src_corners, out_size=None):
    h, w = raw_img.shape[:2]

    if out_size is None:
        width_top    = np.linalg.norm(src_corners[1] - src_corners[0])
        width_bottom = np.linalg.norm(src_corners[2] - src_corners[3])
        height_left  = np.linalg.norm(src_corners[3] - src_corners[0])
        height_right = np.linalg.norm(src_corners[2] - src_corners[1])
        out_w = int(max(width_top, width_bottom))
        out_h = int(max(height_left, height_right))
    else:
        out_w, out_h = out_size

    dst_corners = np.array([
        [0,       0],
        [out_w-1, 0],
        [out_w-1, out_h-1],
        [0,       out_h-1]
    ], dtype=np.float32)

    M = cv.getPerspectiveTransform(src_corners.astype(np.float32), dst_corners)
    warped = cv.warpPerspective(raw_img, M, (out_w, out_h))
    return warped, M
# =====================================================================
# CHECKER — decide if a quad is skewed enough to need correction
# =====================================================================
def quad_needs_perspective_fix(corners, angle_tolerance_deg=4.0, ratio_tolerance=0.04):
    """
    corners: (4,2) array TL,TR,BR,BL
    Returns (needs_fix: bool, score: float) where score is a single
    'how skewed' number (0 = perfect rectangle) you can also use for
    convergence checks across iterations.
    """
    TL, TR, BR, BL = corners

    top    = TR - TL
    bottom = BR - BL
    left   = BL - TL
    right  = BR - TR

    top_len, bottom_len = np.linalg.norm(top), np.linalg.norm(bottom)
    left_len, right_len = np.linalg.norm(left), np.linalg.norm(right)

    # opposite-side length symmetry (1.0 = perfectly equal)
    w_ratio = min(top_len, bottom_len) / max(top_len, bottom_len) if max(top_len, bottom_len) > 0 else 1.0
    h_ratio = min(left_len, right_len) / max(left_len, right_len) if max(left_len, right_len) > 0 else 1.0

    # corner angle deviation from 90°
    def angle_at(p_prev, p_curr, p_next):
        v1 = p_prev - p_curr
        v2 = p_next - p_curr
        cos_a = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-9)
        return np.degrees(np.arccos(np.clip(cos_a, -1.0, 1.0)))

    angles = [
        angle_at(BL, TL, TR),
        angle_at(TL, TR, BR),
        angle_at(TR, BR, BL),
        angle_at(BR, BL, TL),
    ]
    max_angle_dev = max(abs(a - 90) for a in angles)

    ratio_dev = max(1 - w_ratio, 1 - h_ratio)

    needs_fix = (max_angle_dev > angle_tolerance_deg) or (ratio_dev > ratio_tolerance)

    # combined score, useful for convergence comparisons across loop iterations
    score = max_angle_dev + ratio_dev * 100

    return needs_fix, score


# =====================================================================
# DESKEW — Stage A & B and Stage C
# =====================================================================
def deskew_if_needed(img, angle_threshold=5):
    h, w  = img.shape[:2]
    gray  = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    blur  = cv.GaussianBlur(gray, (5, 5), 0)
    block = int(w * 0.02)
    block = block if block % 2 == 1 else block + 1
    block = max(block, 11)

    def get_thresh(image):
        g = cv.cvtColor(image, cv.COLOR_BGR2GRAY)
        b = cv.GaussianBlur(g, (5, 5), 0)
        bk = int(image.shape[1] * 0.02)
        bk = bk if bk % 2 == 1 else bk + 1
        bk = max(bk, 11)
        t  = cv.adaptiveThreshold(b, 255, cv.ADAPTIVE_THRESH_GAUSSIAN_C, cv.THRESH_BINARY_INV, bk, 3)
        return cv.morphologyEx(t, cv.MORPH_CLOSE, np.ones((3,3), np.uint8))

    def find_torso_polygon(image):
        ih, iw = image.shape[:2]
        t      = get_thresh(image)
        conts, _ = cv.findContours(t, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
        candidates = []
        for cnt in conts:
            area = cv.contourArea(cnt)
            if area < ih * iw * 0.02 or area > ih * iw * 0.80:
                continue
            if len(cnt) < 5:
                continue
            hull_area = cv.contourArea(cv.convexHull(cnt))
            solidity  = area / hull_area if hull_area > 0 else 0
            if solidity < 0.70:
                continue
            eps    = 0.02 * cv.arcLength(cnt, True)
            approx = cv.approxPolyDP(cnt, eps, True)
            n      = len(approx)
            if n < 5 or n > 16:
                continue
            x, y, bw, bh = cv.boundingRect(cnt)
            if bw / bh < 0.25 or bw / bh > 2.0:
                continue
            if x < 5 and y < 5 and bw > iw * 0.9:
                continue
            candidates.append((cnt, approx, area, (x, y, bw, bh)))
        if not candidates:
            return None, None, None
        candidates.sort(key=lambda c: c[2], reverse=True)
        cnt, approx, area, bbox = candidates[0]
        return cnt, approx, bbox

    corrected = img.copy()

    # ════════════════════════════════════════════════
    # STAGE A — ROTATION
    # ════════════════════════════════════════════════
    cnt, approx, bbox = find_torso_polygon(corrected)

    if cnt is None:
        print("  Deskew: no polygon found, skipping.")
        return corrected

    pts = approx.reshape(-1, 2).astype(np.float32)
    edge_angles = []
    for i in range(len(pts)):
        p1, p2 = pts[i], pts[(i+1) % len(pts)]
        dx, dy = p2[0]-p1[0], p2[1]-p1[1]
        edge_angles.append((np.sqrt(dx**2+dy**2), np.degrees(np.arctan2(dy, dx))))
    edge_angles.sort(reverse=True)
    norm = edge_angles[0][1] % 180
    if norm > 90: norm -= 180
    rot = norm if abs(norm) <= 45 else (norm-90 if norm > 0 else norm+90)

    print(f"  Deskew: rotation={rot:.1f}°", end="")

    if abs(rot) >= angle_threshold:
        ih, iw = corrected.shape[:2]
        M         = cv.getRotationMatrix2D((iw/2, ih/2), rot, 1.0)
        corrected = cv.warpAffine(corrected, M, (iw, ih),
                                  flags=cv.INTER_CUBIC,
                                  borderMode=cv.BORDER_REPLICATE)
        print(f" → rotated", end="")

    # ════════════════════════════════════════════════
    # STAGE B — AUTO ZOOM (before perspective)
    # ════════════════════════════════════════════════
    res_enhancer_needed = False
    ih, iw     = corrected.shape[:2]
    cnt_z, _, bbox_z = find_torso_polygon(corrected)

    if bbox_z is not None:
        cx, cy, cbw, cbh = bbox_z
        area_ratio = (cbw * cbh) / (iw * ih)
        print(f" | fill={area_ratio:.2f}", end="")

        if area_ratio < 0.3:
            SCALE     = 1.5
            new_w     = int(cbw * SCALE)
            new_h     = int(cbh * SCALE)

            pc_x      = cx + cbw // 2
            pc_y      = cy + cbh // 2
            PAD       = int(max(new_w, new_h) * 0.08)

            x1 = max(0,  pc_x - new_w // 2 - PAD)
            y1 = max(0,  pc_y - new_h // 2 - PAD)
            x2 = min(iw, pc_x + new_w // 2 + PAD)
            y2 = min(ih, pc_y + new_h // 2 + PAD)

            corrected = corrected[y1:y2, x1:x2]
            print(f" → zoomed to {x2-x1}×{y2-y1}", end="")
            res_enhancer_needed = True

        else:
            print(f" → no zoom needed", end="")
    else:
        print(f" | no polygon for zoom", end="")

    # ════════════════════════════════════════════════
    # STAGE C — PERSPECTIVE, now with need-checking + convergence loop
    # ════════════════════════════════════════════════
    was_perspective_corrected = False
    perspective_iterations = 0

    MAX_PERSPECTIVE_ITERS = 2          # hard cap so it can never loop forever
    SCORE_IMPROVEMENT_MIN = 1        # stop if score stops improving by at least this much

    prev_score = None

    for _iter in range(MAX_PERSPECTIVE_ITERS):
        unique_contours, detected_objects = detect_target_shapes(corrected)

        target_contour = None
        for c, obj in zip(unique_contours, detected_objects):
            if "8 pts" in obj["type"]:
                target_contour = c
                break

        if target_contour is None or not unique_contours:
            if _iter == 0:
                print(f" → no 8-pt octagon contour found, skipping perspective", end="")
            break

        try:
            corners = get_octagon_corners(target_contour, corrected.shape, debug=False)
        except ValueError as e:
            if _iter == 0:
                print(f" → perspective skipped ({e})", end="")
            break
        try:
            corners = get_octagon_corners(target_contour, corrected.shape, debug=False)
        except ValueError as e:
            if _iter == 0:
                print(f" → perspective skipped ({e})", end="")
            break

        needs_fix, score = quad_needs_perspective_fix(corners)
        needs_fix, score = quad_needs_perspective_fix(corners)

        if not needs_fix:
            if _iter == 0:
                print(f" → no perspective fix needed (score={score:.2f})", end="")
            else:
                print(f" → converged after {_iter} pass(es) (score={score:.2f})", end="")
            break

        if prev_score is not None and (prev_score - score) < SCORE_IMPROVEMENT_MIN:
            print(f" → stopping, improvement plateaued (prev={prev_score:.2f} now={score:.2f})", end="")
            break

        outer_torso_contour = max(zip(unique_contours, detected_objects), key=lambda t: t[1]["area"])[0]
        torso_pts = outer_torso_contour.reshape(-1, 2)
        expanded_corners, k_used = expand_quad_to_fit_contour(corners, torso_pts, padding_ratio=0.03)

        corrected, _ = warp_from_corners(corrected, expanded_corners)
        was_perspective_corrected = True
        perspective_iterations += 1
        prev_score = score
        print(f" → perspective pass {_iter+1} (score={score:.2f}, scale={k_used:.2f})", end="")
        res_enhancer_needed = True

    print(f" | total perspective passes: {perspective_iterations}", end="")

    # ════════════════════════════════════════════════
    # STAGE D — RESOLUTION ENHANCEMENT (only if zoomed or warped)
    # ════════════════════════════════════════════════
    if res_enhancer_needed:
      if corrected.shape is not 850:

        target_width = 850   # <-- set to None to skip resizing
        ratio           = corrected.shape[0] / corrected.shape[1]
        target_height   = 1550
        interp          = cv.INTER_LANCZOS4 if target_width < corrected.shape[1] else cv.INTER_CUBIC
        corrected        = cv.resize(corrected, (target_width, target_height), interpolation=interp)
        print(f" → enhancing resolution (perspective={corrected.shape[0]} x {corrected.shape[1]} ratio: {ratio})", end="")

    print()
    return corrected

# =====================================================================
# Loop for all the img paths to deskew
# =====================================================================

deskewed_imgs = []
"""
raw_img = deskew_if_needed(raw_img, angle_threshold=10)
plt.subplot(1,2,2)
plt.imshow(raw_img)
"""

for img_path in image_paths:
    raw_im = cv.imread(img_path)

    if raw_im is None:
        print(f"Error: Could not load {img_path}")
        continue

    print(f"Processing {img_path}...", end="")

    processed_img = deskew_if_needed(raw_im, angle_threshold=10)
    deskewed_imgs.append(processed_img)

print(f"\nSuccessfully processed and stored {len(deskewed_imgs)} images.")

num_images = len(deskewed_imgs)
fig, axes  = plt.subplots(num_images, 2, figsize=(12, num_images * 6))

for img_idx, (raw_path, raw_img) in enumerate(zip(image_paths, deskewed_imgs)):
    raw_original = cv.imread(raw_path)


    # =====================================================================
    # 1. PREPROCESSING (Clean Edge & Shape Discovery)
    # =====================================================================

    gray = cv.cvtColor(raw_img, cv.COLOR_BGR2GRAY)
    blur = cv.GaussianBlur(gray, (5, 5), 0)

    # 2. Simplified Adaptive Threshold (The Scalpel)
    block = int(raw_img.shape[1] * 0.02)
    block = block if block % 2 == 1 else block + 1
    block = max(block, 11)

    # Notice the last number is '2' instead of '3'. Lowering this makes it
    # slightly more sensitive, helping it catch faint lines on dark black targets.
    thresh_clean = cv.adaptiveThreshold(
        blur, 255, cv.ADAPTIVE_THRESH_GAUSSIAN_C,
        cv.THRESH_BINARY_INV, block, 2
    )

    # 3. Light Cleanup
    # Shrunk the kernel to (2, 2). A (3, 3) kernel was too thick and was causing
    # nearby lines (like the head and torso) to accidentally merge together.
    kernel = cv.getStructuringElement(cv.MORPH_RECT, (2, 2))
    thresh_clean = cv.morphologyEx(thresh_clean, cv.MORPH_CLOSE, kernel)

    # 4. Find Contours
    contours, hierarchy = cv.findContours(
        thresh_clean, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE
    )



    # =====================================================================
    # 2. FILTERING TEXT & DETECTING UNIQUE TARGET SHAPES
    # =====================================================================

    # ── Image scale factor — all thresholds derive from this ────────────
    # Everything is relative to image area so any resolution works
    IMG_AREA      = raw_img.shape[0] * raw_img.shape[1]
    IMG_DIAG      = (raw_img.shape[0]**2 + raw_img.shape[1]**2) ** 0.5

    # Scale-relative thresholds (tune the multipliers, not the raw numbers)
    MIN_AREA      = IMG_AREA * 0.002
    PERIM_LARGE   = IMG_DIAG * 0.5
    SPIKE_MAX_LEN = IMG_DIAG * 0.1
    TOLERANCE_PX  = int(IMG_DIAG * 0.02)

    unique_contours = []
    seen_boxes = []
    detected_objects = []
    for cnt in contours:
        area = cv.contourArea(cnt)
        perimeter = cv.arcLength(cnt, True)
        # 1. Skip tiny noise and small artifacts
        if area < MIN_AREA:
            continue

        compactness = (perimeter ** 2) / area if area > 0 else 9999
        if compactness > 500 and area < IMG_AREA * 0.05:      # tune up if real shapes get filtered, down if noise stays
            continue

        x, y, w, h = cv.boundingRect(cnt)

        # Calculate aspect ratio
        aspect_ratio = float(w) / h if h > 0 else 0

        # FIX CONTOUR #2: Instantly drop thin line fragments
        if aspect_ratio < 0.15 or aspect_ratio > 6.0:
            continue

        # Calculate solidity
        hull = cv.convexHull(cnt)
        hull_area = cv.contourArea(hull)
        solidity = float(area) / hull_area if hull_area > 0 else 0

        # Skip low solidity text layout lines
        if solidity < 0.40:
            continue

        # 2. Deduplicate close edge tracks
        is_duplicate = False
        for sx, sy, sw, sh in seen_boxes:
            if (abs(x - sx) < TOLERANCE_PX and
                abs(y - sy) < TOLERANCE_PX and
                abs(w - sw) < TOLERANCE_PX and
                abs(h - sh) < TOLERANCE_PX):
                is_duplicate = True
                break

        if not is_duplicate:
            seen_boxes.append((x, y, w, h))

            # 1. Math Check: Is this a round circle or a polygon shape?
            ellipse = cv.fitEllipse(cnt) if len(cnt) >= 5 else None
            is_circle = False

            if ellipse:
                (_, _), (ew, eh), _ = ellipse
                circle_ratio = float(ew) / eh if eh > 0 else 0

                rect = cv.minAreaRect(cnt)
                rect_area = rect[1][0] * rect[1][1]
                rect_extent = float(area) / rect_area if rect_area > 0 else 0

                test_epsilon = 0.01 * cv.arcLength(cnt, True)
                test_approx = cv.approxPolyDP(cnt, test_epsilon, True)
                num_vertices = len(test_approx)

                if (0.65 < circle_ratio < 1.50 and
                    0.72 <= rect_extent <= 0.82 and
                    num_vertices > 8 and
                    solidity > 0.95):
                    is_circle = True
            else:
                test_epsilon = 0.01 * cv.arcLength(cnt, True)
                test_approx  = cv.approxPolyDP(cnt, test_epsilon, True)
                num_vertices = len(test_approx)

            # ── Classify shape type ──────────────────────────────────
            if is_circle:
                (_, _), (ew, eh), _ = ellipse
                cr = float(ew) / eh if eh > 0 else 0
                shape_type = "circle" if 0.90 < cr < 1.10 else "ellipse"


            # ── Build clean contour ──────────────────────────────────
            contour_to_add = None

            if is_circle:
                smooth = cv.ellipse2Poly(
                    (int(ellipse[0][0]), int(ellipse[0][1])),
                    (int(ew / 2), int(eh / 2)),
                    int(ellipse[2]),
                    0, 360, 4
                )
                contour_to_add = smooth.reshape(-1, 1, 2)

            else:
                perimeter = cv.arcLength(cnt, True)

                if perimeter > PERIM_LARGE:
                    isolated_canvas = np.zeros_like(thresh_healed)
                    cv.drawContours(isolated_canvas, [cnt], -1, 255, -1)

                    k_size = np.clip(
                        int(perimeter * 0.003) + (1 if int(perimeter * 0.003) % 2 == 0 else 0),
                        3, 15
                    )
                    kernel_e = cv.getStructuringElement(cv.MORPH_ELLIPSE, (k_size, k_size))
                    cleaned_canvas = cv.morphologyEx(isolated_canvas, cv.MORPH_OPEN,  kernel_e)
                    cleaned_canvas = cv.morphologyEx(cleaned_canvas,  cv.MORPH_CLOSE, kernel_e)

                    smoothed_contours, _ = cv.findContours(
                        cleaned_canvas, cv.RETR_EXTERNAL, cv.CHAIN_APPROX_SIMPLE
                    )

                    if smoothed_contours:
                        main_smoothed_cnt = max(smoothed_contours, key=cv.contourArea)
                        current_area = cv.contourArea(cnt)
                        largest_area = max([cv.contourArea(c) for c in unique_contours]) if unique_contours else 0

                        if current_area >= largest_area:
                            epsilon = 0.005 * cv.arcLength(main_smoothed_cnt, True)
                            approx  = cv.approxPolyDP(main_smoothed_cnt, epsilon, True)

                            # --- NEW: Get bounding dimensions to protect shoulders ---
                            x_box, y_box, w_box, h_box = cv.boundingRect(main_smoothed_cnt)

                            idx = 0
                            while idx < len(approx) and len(approx) > 4:
                                p_curr = approx[idx][0]
                                p_prev = approx[idx - 1][0]
                                p_next = approx[(idx + 1) % len(approx)][0]

                                len_prev = np.linalg.norm(p_curr - p_prev)
                                len_next = np.linalg.norm(p_curr - p_next)

                                if len_prev < SPIKE_MAX_LEN and len_next < SPIKE_MAX_LEN:
                                    v1 = p_prev - p_curr
                                    v2 = p_next - p_curr
                                    cos_angle = np.dot(v1, v2) / (
                                        np.linalg.norm(v1) * np.linalg.norm(v2) + 1e-6
                                    )
                                    angle = np.degrees(np.arccos(np.clip(cos_angle, -1.0, 1.0)))

                                    in_upper_zone = (p_curr[1] < y_box + h_box * 0.40)

                                    in_head_zone = (
                                        (p_curr[1] < y_box + h_box * 0.25) and
                                        (p_curr[0] > x_box + w_box * 0.35) and
                                        (p_curr[0] < x_box + w_box * 0.65)
                                    )

                                    is_shoulder_corner = (
                                        (p_curr[1] < y_box + h_box * 0.40) and
                                        ((p_curr[0] < x_box + w_box * 0.30) or (p_curr[0] > x_box + w_box * 0.70))
                                    )

                                    should_protect = in_upper_zone or in_head_zone or is_shoulder_corner

                                    if angle < 115 and not should_protect:
                                        approx = np.delete(approx, idx, axis=0)
                                        continue
                                idx += 1
                            contour_to_add = approx

                        else:
                            hull = cv.convexHull(main_smoothed_cnt)
                            epsilon = 0.01 * cv.arcLength(hull, True)
                            contour_to_add = cv.approxPolyDP(hull, epsilon, True)

                else:
                    clean_hull = cv.convexHull(cnt)
                    epsilon    = 0.006 * cv.arcLength(clean_hull, True)
                    contour_to_add = cv.approxPolyDP(clean_hull, epsilon, True)

            # ── Single append point — lists always stay in sync ──────
            # ── Single append point — classify AFTER all cleaning ────
            if contour_to_add is not None:

                # Count vertices on the FINAL cleaned contour, not the raw one
                # This gives accurate vertex count after bullet hole fixing
                if is_circle:
                    (_, _), (ew, eh), _ = ellipse
                    cr = float(ew) / eh if eh > 0 else 0
                    shape_type = "circle" if 0.90 < cr < 1.10 else "ellipse"
                else:
                    # Re-approximate the final contour at a clean epsilon
                    final_epsilon  = 0.02 * cv.arcLength(contour_to_add, True)
                    final_approx   = cv.approxPolyDP(contour_to_add, final_epsilon, True)
                    final_vertices = len(final_approx)

                    if final_vertices == 3:
                        shape_type = "triangle"
                    elif final_vertices == 4:
                        shape_type = "square" if 0.90 < aspect_ratio < 1.10 else "rectangle"
                    elif final_vertices <= 8:
                        shape_type = f"polygon ({final_vertices} pts)"
                    else:
                        shape_type = "polygon"

                unique_contours.append(contour_to_add)
                detected_objects.append({
                    "type":  shape_type,
                    "index": len(unique_contours) - 1,
                    "area":  cv.contourArea(contour_to_add)
                })


    # =====================================================================
    # POST-LOOP NOISE REMOVAL
    # Remove shapes that are too small relative to the largest detected shape
    # =====================================================================
    if unique_contours:
        largest_area = max(obj["area"] for obj in detected_objects)

        # Keep only shapes that are at least 2% of the largest shape's area
        # Tune DOWN to 0.01 if small real shapes get removed
        # Tune UP to 0.05 if noise still slips through
        MIN_RELATIVE_AREA = largest_area * 0.02

        filtered_pairs = [
            (cnt, obj)
            for cnt, obj in zip(unique_contours, detected_objects)
            if obj["area"] >= MIN_RELATIVE_AREA
        ]

        if filtered_pairs:
            unique_contours, detected_objects = map(list, zip(*filtered_pairs))
        else:
            unique_contours, detected_objects = [], []
    # =====================================================================
    # NEW CODE: REMOVE THE SECOND-LARGEST SHAPE
    # =====================================================================
    if len(detected_objects) >= 2:
        # 1. Pair objects with their original list indices
        indexed_objects = list(enumerate(detected_objects))

        # 2. Sort by area from largest to smallest
        indexed_objects.sort(key=lambda x: x[1]["area"], reverse=True)

        # 3. Identify the original index and details of the second largest shape
        second_largest_original_idx = indexed_objects[1][0]
        second_largest_shape = indexed_objects[1][1]

        # 4. Safety Check: Only delete if it's the inner polygon
        # Checked for "polygon" or "8 pts" just in case your naming varies
        if "polygon" in second_largest_shape["type"] or "8 pts" in second_largest_shape["type"]:
            detected_objects.pop(second_largest_original_idx)
            unique_contours.pop(second_largest_original_idx)

            # 5. Fix the indices stored inside the remaining dictionaries
            for i, obj in enumerate(detected_objects):
                obj["index"] = i
    # =====================================================================
    # 3. DYNAMIC PLOTTING GRID (View All Discovered Shapes Separately)
    # =====================================================================
    num_contours = len(unique_contours)

    if num_contours == 0:
        print("No target shapes found to plot!")
    else:
        cols = min(4, num_contours)
        rows = math.ceil(num_contours / cols)
        plt.figure(figsize=(cols * 4, rows * 4))
    overlay = raw_img.copy()
    cv.drawContours(overlay, unique_contours, -1, (0,0,255), 4)

    axes[img_idx, 0].imshow(cv.cvtColor(raw_original, cv.COLOR_BGR2RGB))
    axes[img_idx, 0].set_title(f"Raw Image #{img_idx+1}")
    axes[img_idx, 0].axis("off")

    axes[img_idx, 1].imshow(cv.cvtColor(overlay, cv.COLOR_BGR2RGB))
    axes[img_idx, 1].set_title(f"{len(unique_contours)} Shapes Detected")
    axes[img_idx, 1].axis("off")

plt.tight_layout()
plt.show()